Remove V1 for SA360
google-marketing-solutions/margin-protection pull request #12
Opened 2024-08-05 16:56 UTC by smcjones

2024-08-05 17:02 UTC, smcjones commented
This should be reviewed AFTER https://github.com/google-marketing-solutions/margin-protection/pull/13

2024-08-06 16:16 UTC, anaesqueda requested changes
Hi Sean, looks like there are some merge comments in this PR, could you please remove them? Thanks!

2024-08-06 17:18 UTC, smcjones commented on sa360/src/api.ts
> +<<<<<<< HEAD
HI @anaesqueda build was failing due to this and it should already be fixed.

2024-08-06 17:24 UTC, anaesqueda approved these changes
LGTM

2024-08-06 17:44 UTC, merged